5-raise_exception.py
